//! Research state model for iterative, multi-pass research sessions.
//!
//! This module defines the in-memory data model required by FR-007:
//! while a research session is in progress the session state tracks the
//! current plan, sub-question statuses, gathered sources, evaluation score,
//! iteration count, and pending evidence gaps.
//!
//! The structures are intentionally serializable so that later tasks (T-013,
//! T-012) can persist and resume a `ResearchState` to/from disk.

use crate::source::Source;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// The full state of an in-progress research session.
///
/// `ResearchState` is the single source of truth for the iterative research
/// loop. It is updated by the planner (sub-questions), the gatherers
/// (`sources`), the critic/evaluator (`evaluation_score`), and the
/// missing-link detector (`gaps`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct ResearchState {
    /// Current research plan: topic plus focused sub-questions.
    pub plan: ResearchPlan,
    /// Number of completed retrieval/synthesis iterations.
    pub iteration_count: u32,
    /// Latest quality score produced by the evaluation step, if any.
    /// Higher is better; the exact scale is left to the evaluator.
    pub evaluation_score: Option<u32>,
    /// All sources captured so far (web, local, spec, other).
    pub sources: Vec<Source>,
    /// Known evidence gaps that still need to be closed.
    pub gaps: Vec<EvidenceGap>,
    /// Follow-up queries generated by the missing-link detector.
    pub follow_up_queries: Vec<String>,
    /// Recorded source-fetch failures (FR-006).
    pub failed_attempts: Vec<FailedSource>,
}

impl ResearchState {
    /// Create a fresh state for `topic` with an empty plan.
    pub fn new(topic: impl Into<String>) -> Self {
        Self {
            plan: ResearchPlan::new(topic),
            ..Self::default()
        }
    }

    /// Return `true` when every sub-question has been answered and there are
    /// no unresolved evidence gaps.
    #[must_use]
    pub fn is_complete(&self) -> bool {
        !self.plan.sub_questions.is_empty()
            && self
                .plan
                .sub_questions
                .iter()
                .all(|sq| sq.status == SubQuestionStatus::Answered)
            && self.gaps.iter().all(|g| g.resolved)
    }

    /// Return the sub-questions that still need work.
    #[must_use]
    pub fn pending_sub_questions(&self) -> Vec<&SubQuestion> {
        self.plan
            .sub_questions
            .iter()
            .filter(|sq| sq.status.is_pending())
            .collect()
    }

    /// Return the unresolved evidence gaps.
    #[must_use]
    pub fn active_gaps(&self) -> Vec<&EvidenceGap> {
        self.gaps.iter().filter(|g| !g.resolved).collect()
    }

    /// Increment the iteration counter and return the new value.
    pub const fn increment_iteration(&mut self) -> u32 {
        self.iteration_count += 1;
        self.iteration_count
    }

    /// Record the latest evaluation score.
    pub const fn set_evaluation_score(&mut self, score: u32) {
        self.evaluation_score = Some(score);
    }

    /// Add a captured source to the state, replacing any existing source with
    /// the same stable identifier (web URL, local path, or spec id).
    pub fn add_source(&mut self, source: Source) {
        if let Some(existing) = self.sources.iter_mut().find(|s| same_source(s, &source)) {
            *existing = source;
            return;
        }
        self.sources.push(source);
    }

    /// Append a focused sub-question to the plan.
    pub fn add_sub_question(
        &mut self,
        id: impl Into<String>,
        question: impl Into<String>,
        priority: u8,
    ) {
        self.plan.sub_questions.push(SubQuestion {
            id: id.into(),
            question: question.into(),
            status: SubQuestionStatus::Pending,
            priority,
        });
    }

    /// Update the status of a sub-question by id.
    ///
    /// Returns `true` if the id existed and was updated.
    pub fn set_sub_question_status(&mut self, id: &str, status: SubQuestionStatus) -> bool {
        if let Some(sq) = self.plan.sub_questions.iter_mut().find(|sq| sq.id == id) {
            sq.status = status;
            true
        } else {
            false
        }
    }

    /// Record a new evidence gap.
    pub fn add_gap(
        &mut self,
        id: impl Into<String>,
        description: impl Into<String>,
        sub_question_ids: Vec<String>,
    ) {
        self.gaps.push(EvidenceGap {
            id: id.into(),
            description: description.into(),
            sub_question_ids,
            resolved: false,
        });
    }

    /// Mark an evidence gap as resolved by id.
    ///
    /// Returns `true` if the id existed and was unresolved.
    pub fn resolve_gap(&mut self, id: &str) -> bool {
        if let Some(gap) = self.gaps.iter_mut().find(|g| g.id == id && !g.resolved) {
            gap.resolved = true;
            true
        } else {
            false
        }
    }

    /// Apply a user follow-up message to an in-progress state (T-014).
    ///
    /// The message is appended to the topic and added as a new high-priority
    /// pending sub-question so the next iteration will gather evidence for it.
    pub fn apply_follow_up(&mut self, message: impl Into<String>) {
        let msg = message.into();
        let id = format!("follow-up-{}", self.plan.sub_questions.len() + 1);
        self.plan.topic.push_str(&format!("\n\nFollow-up: {msg}"));
        self.add_sub_question(&id, &msg, 10);
        self.set_sub_question_status(&id, SubQuestionStatus::Pending);
    }

    /// Add a follow-up query produced by the missing-link detector.
    pub fn add_follow_up_query(&mut self, query: impl Into<String>) {
        let q = query.into();
        if !q.is_empty() && !self.follow_up_queries.contains(&q) {
            self.follow_up_queries.push(q);
        }
    }

    /// Record a source-fetch failure in session state (FR-006).
    pub fn record_failed_source(
        &mut self,
        source: Option<impl Into<String>>,
        error: impl Into<String>,
    ) {
        self.failed_attempts.push(FailedSource {
            source: source.map(Into::into),
            error: error.into(),
            at: Utc::now(),
        });
    }

    /// A snapshot of counts useful for progress rendering.
    #[must_use]
    pub fn counts(&self) -> StateCounts {
        StateCounts {
            sub_questions_total: self.plan.sub_questions.len(),
            sub_questions_answered: self
                .plan
                .sub_questions
                .iter()
                .filter(|sq| sq.status == SubQuestionStatus::Answered)
                .count(),
            sources_total: self.sources.len(),
            gaps_total: self.gaps.len(),
            gaps_active: self.active_gaps().len(),
            follow_ups_total: self.follow_up_queries.len(),
            iteration_count: self.iteration_count,
            evaluation_score: self.evaluation_score,
            failed_attempts_total: self.failed_attempts.len(),
        }
    }
}

/// A recorded source-fetch failure (FR-006).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct FailedSource {
    /// Source identifier (URL, path, or label) if known.
    pub source: Option<String>,
    /// Human-readable error message.
    pub error: String,
    /// UTC timestamp of the failure.
    pub at: DateTime<Utc>,
}

/// Counts summarising a `ResearchState` for progress views.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct StateCounts {
    /// Total number of planned sub-questions.
    pub sub_questions_total: usize,
    /// Sub-questions that have reached [`SubQuestionStatus::Answered`].
    pub sub_questions_answered: usize,
    /// Total captured sources.
    pub sources_total: usize,
    /// Total evidence gaps recorded.
    pub gaps_total: usize,
    /// Evidence gaps that are still unresolved.
    pub gaps_active: usize,
    /// Follow-up queries awaiting retrieval.
    pub follow_ups_total: usize,
    /// Completed iterations of the research loop.
    pub iteration_count: u32,
    /// Latest evaluation score, if any.
    pub evaluation_score: Option<u32>,
    /// Recorded source-fetch failures.
    pub failed_attempts_total: usize,
}

/// The research plan: the original topic decomposed into focused
/// sub-questions.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct ResearchPlan {
    /// Free-form topic or question that the user wants researched.
    pub topic: String,
    /// Focused sub-questions that drive retrieval and synthesis.
    pub sub_questions: Vec<SubQuestion>,
}

impl ResearchPlan {
    /// Create an empty plan for `topic`.
    pub fn new(topic: impl Into<String>) -> Self {
        Self {
            topic: topic.into(),
            sub_questions: Vec::new(),
        }
    }

    /// Return sub-questions grouped by status for progress rendering.
    #[must_use]
    pub fn status_counts(&self) -> HashMap<String, usize> {
        let mut counts = HashMap::new();
        for sq in &self.sub_questions {
            *counts.entry(sq.status.as_str().to_string()).or_insert(0) += 1;
        }
        counts
    }
}

/// One focused sub-question inside a [`ResearchPlan`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct SubQuestion {
    /// Stable identifier used to link gaps and follow-ups back to this
    /// question.
    pub id: String,
    /// Human-readable question text.
    pub question: String,
    /// Current lifecycle status.
    pub status: SubQuestionStatus,
    /// Priority: higher values mean more important. Used by the scheduler
    /// when deciding which sub-question to tackle next.
    pub priority: u8,
}

/// Lifecycle status of a sub-question.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum SubQuestionStatus {
    /// Created but not yet being worked on.
    #[default]
    Pending,
    /// Actively being searched or synthesized.
    InProgress,
    /// Sufficient evidence has been gathered and a finding recorded.
    Answered,
    /// Cannot be answered because a dependency or source is missing.
    Blocked,
}

impl SubQuestionStatus {
    /// Returns `true` for [`Pending`] and [`Blocked`] — states that still
    /// need attention.
    ///
    /// [`Pending`]: Self::Pending
    /// [`Blocked`]: Self::Blocked
    #[must_use]
    pub const fn is_pending(self) -> bool {
        matches!(self, Self::Pending | Self::Blocked)
    }

    /// Snake-case label used in YAML/JSON rendering.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::InProgress => "in_progress",
            Self::Answered => "answered",
            Self::Blocked => "blocked",
        }
    }
}

/// A missing piece of evidence that the critic/verifier has identified.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct EvidenceGap {
    /// Stable identifier for the gap.
    pub id: String,
    /// Human-readable description of what is missing (e.g. "no primary
    /// source for the 2023 figure").
    pub description: String,
    /// Sub-question ids that depend on this gap.
    pub sub_question_ids: Vec<String>,
    /// `true` once a follow-up retrieval has closed the gap.
    pub resolved: bool,
}

/// Determine whether two sources refer to the same evidence.
fn same_source(left: &Source, right: &Source) -> bool {
    match (left, right) {
        (Source::Web { url: l, .. }, Source::Web { url: r, .. }) => l == r,
        (Source::Local { path: l, .. }, Source::Local { path: r, .. }) => l == r,
        (Source::Spec { spec_id: l, .. }, Source::Spec { spec_id: r, .. }) => l == r,
        (Source::Other { label: l, .. }, Source::Other { label: r, .. }) => l == r,
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::source::{LocalSourceKind, Source};
    use chrono::Utc;
    use std::path::PathBuf;

    fn web_source(url: &str) -> Source {
        Source::Web {
            published_at: None,
            url: url.to_string(),
            title: "title".to_string(),
            captured_at: Utc::now(),
            body_path: PathBuf::from("sources/web-01.md"),
            body: "body".to_string(),
            relevance: String::new(),
            search_tool: String::new(),
            search_engine: String::new(),
            content_type: None,
            page_type: None,
            media_type: "page".into(),
            language: None,
        }
    }

    #[test]
    fn test_state_starts_empty() {
        let state = ResearchState::new("Rust async runtimes");
        assert_eq!(state.plan.topic, "Rust async runtimes");
        assert!(state.plan.sub_questions.is_empty());
        assert!(state.sources.is_empty());
        assert!(state.gaps.is_empty());
        assert_eq!(state.iteration_count, 0);
        assert!(state.evaluation_score.is_none());
    }

    #[test]
    fn test_add_and_update_sub_question() {
        let mut state = ResearchState::new("topic");
        state.add_sub_question("q1", "What is tokio?", 10);
        assert_eq!(state.pending_sub_questions().len(), 1);

        assert!(state.set_sub_question_status("q1", SubQuestionStatus::InProgress));
        assert_eq!(
            state.plan.sub_questions[0].status,
            SubQuestionStatus::InProgress
        );

        assert!(state.set_sub_question_status("q1", SubQuestionStatus::Answered));
        assert!(state.is_complete());
        assert!(!state.set_sub_question_status("missing", SubQuestionStatus::Answered));
    }

    #[test]
    fn test_complete_requires_no_active_gaps() {
        let mut state = ResearchState::new("topic");
        state.add_sub_question("q1", "question", 1);
        state.set_sub_question_status("q1", SubQuestionStatus::Answered);

        state.add_gap("g1", "missing citation", vec!["q1".to_string()]);
        assert!(!state.is_complete());

        assert!(state.resolve_gap("g1"));
        assert!(state.is_complete());
        assert!(!state.resolve_gap("g1"));
    }

    #[test]
    fn test_source_deduplication() {
        let mut state = ResearchState::new("topic");
        state.add_source(web_source("https://example.com/a"));
        state.add_source(web_source("https://example.com/a"));
        assert_eq!(state.sources.len(), 1);
    }

    #[test]
    fn test_counts() {
        let mut state = ResearchState::new("topic");
        state.add_sub_question("q1", "a", 1);
        state.add_sub_question("q2", "b", 1);
        state.set_sub_question_status("q1", SubQuestionStatus::Answered);
        state.add_source(web_source("https://example.com"));
        state.add_gap("g1", "gap", vec![]);
        state.increment_iteration();
        state.set_evaluation_score(72);

        let counts = state.counts();
        assert_eq!(counts.sub_questions_total, 2);
        assert_eq!(counts.sub_questions_answered, 1);
        assert_eq!(counts.sources_total, 1);
        assert_eq!(counts.gaps_total, 1);
        assert_eq!(counts.gaps_active, 1);
        assert_eq!(counts.iteration_count, 1);
        assert_eq!(counts.evaluation_score, Some(72));
        assert_eq!(counts.failed_attempts_total, 0);
    }

    #[test]
    fn test_record_failed_source() {
        let mut state = ResearchState::new("topic");
        state.record_failed_source(Some("https://x.com"), "timeout");
        assert_eq!(state.failed_attempts.len(), 1);
        assert_eq!(
            state.failed_attempts[0].source.as_deref(),
            Some("https://x.com")
        );
        assert_eq!(state.counts().failed_attempts_total, 1);
    }
    #[test]
    fn test_plan_status_counts() {
        let mut plan = ResearchPlan::new("topic");
        plan.sub_questions.push(SubQuestion {
            id: "q1".into(),
            question: "a".into(),
            status: SubQuestionStatus::Answered,
            priority: 1,
        });
        plan.sub_questions.push(SubQuestion {
            id: "q2".into(),
            question: "b".into(),
            status: SubQuestionStatus::Pending,
            priority: 1,
        });
        let counts = plan.status_counts();
        assert_eq!(counts.get("answered"), Some(&1));
        assert_eq!(counts.get("pending"), Some(&1));
    }

    #[test]
    fn test_same_source_local() {
        let a = Source::Local {
            path: "src/lib.rs".to_string(),
            kind: LocalSourceKind::InProject,
            captured_at: Utc::now(),
            body_path: PathBuf::from("sources/local-01.md"),
            relevance: "high".to_string(),
            body: "body".to_string(),
        };
        let b = Source::Local {
            path: "src/lib.rs".to_string(),
            kind: LocalSourceKind::InProject,
            captured_at: Utc::now(),
            body_path: PathBuf::from("sources/local-02.md"),
            relevance: "medium".to_string(),
            body: "other".to_string(),
        };
        assert!(same_source(&a, &b));
    }
}
