//! Tier router for Hyperresearch-style runs (T-005, FR-005, FR-008).
//!
//! A [`TierRouter`] turns the selected [`Tier`](crate::run_config::Tier) into
//! an ordered sequence of [`RunStep`](crate::run_manifest::RunStep) entries in a
//! [`RunManifest`](crate::run_manifest::RunManifest). It drives the run through
//! each step, emitting progress events so the TUI/CLI can display which
//! pipeline stage is active.
//!
//! The router intentionally does not contain the step implementations; it only
//! tracks which steps are required, which are skipped, and which are complete.
//! The [`ResearchSession`](crate::session::ResearchSession) maps concrete work
//! (gathering, synthesis, citation checking) onto the corresponding steps.

use crate::run_config::{ResearchMode, Tier};
use crate::run_manifest::{RunManifest, RunStep, StepStatus};
use std::sync::Arc;

/// Observer callback for tier-router progress.
///
/// Implementors receive one event per step transition plus a summary event when
/// the run finishes.
pub trait TierRouterObserver: Send + Sync {
    /// Called whenever a step starts, completes, skips, or fails.
    fn on_step(&self, step: RunStep, status: StepStatus, detail: Option<String>);
    /// Called when the whole run reaches a terminal state.
    fn on_done(&self, completed: usize, skipped: usize, failed: usize);
}

/// No-op observer for tests and headless runs.
pub struct NoopTierRouterObserver;

impl TierRouterObserver for NoopTierRouterObserver {
    fn on_step(&self, _step: RunStep, _status: StepStatus, _detail: Option<String>) {}
    fn on_done(&self, _completed: usize, _skipped: usize, _failed: usize) {}
}

/// Simple observer that collects step transitions into a vector for inspection.
#[cfg(test)]
pub struct CollectingTierRouterObserver {
    events: std::sync::Mutex<Vec<(RunStep, StepStatus, Option<String>)>>,
}

#[cfg(test)]
impl CollectingTierRouterObserver {
    fn new() -> Self {
        Self {
            events: std::sync::Mutex::new(Vec::new()),
        }
    }

    fn events(&self) -> Vec<(RunStep, StepStatus, Option<String>)> {
        self.events.lock().unwrap().clone()
    }
}

#[cfg(test)]
impl TierRouterObserver for CollectingTierRouterObserver {
    fn on_step(&self, step: RunStep, status: StepStatus, detail: Option<String>) {
        self.events.lock().unwrap().push((step, status, detail));
    }
    fn on_done(&self, _completed: usize, _skipped: usize, _failed: usize) {}
}

/// Coordinates execution of the tier-specific research pipeline.
///
/// The router owns a [`RunManifest`] and walks it from the first pending step
/// to the last. Callers call [`start_step`](Self::start_step) before the
/// concrete work and [`finish_step`](Self::finish_step) / [`skip_step`](Self::skip_step)
/// / [`fail_step`](Self::fail_step) afterward.
#[derive(Debug, Clone)]
pub struct TierRouter {
    manifest: RunManifest,
}

impl TierRouter {
    /// Create a fresh router for `name`/`topic` at the given tier in tiered mode.
    ///
    /// The `run_tag` is generated by the caller and is used as the vault
    /// directory name.
    #[must_use]
    pub fn new(
        run_tag: impl Into<String>,
        name: impl Into<String>,
        topic: impl Into<String>,
        tier: Tier,
    ) -> Self {
        Self::new_with_mode(run_tag, name, topic, tier, ResearchMode::Tiered)
    }

    /// Create a fresh router for `name`/`topic` at the given tier and mode.
    ///
    /// Supervisor and competitive modes use the supervisor/researcher graph
    /// steps (FR-009); tiered mode uses the classic tiered pipeline.
    #[must_use]
    pub fn new_with_mode(
        run_tag: impl Into<String>,
        name: impl Into<String>,
        topic: impl Into<String>,
        tier: Tier,
        mode: ResearchMode,
    ) -> Self {
        Self {
            manifest: RunManifest::new_with_mode(run_tag, name, topic, tier, mode),
        }
    }

    /// Wrap an existing manifest, e.g. when resuming an interrupted run.
    #[must_use]
    pub fn from_manifest(manifest: RunManifest) -> Self {
        Self { manifest }
    }

    /// Borrow the underlying manifest.
    #[must_use]
    pub fn manifest(&self) -> &RunManifest {
        &self.manifest
    }

    /// Mutably borrow the underlying manifest.
    pub fn manifest_mut(&mut self) -> &mut RunManifest {
        &mut self.manifest
    }

    /// Return the tier selected for this run.
    #[must_use]
    pub fn tier(&self) -> Tier {
        self.manifest.tier
    }

    /// Return the mode selected for this run.
    #[must_use]
    pub fn mode(&self) -> ResearchMode {
        self.manifest.mode
    }

    /// Return the next step that should run, if any.
    ///
    /// Skips steps that are not part of the current tier and returns the first
    /// pending or failed step.
    #[must_use]
    pub fn next_step(&self) -> Option<RunStep> {
        self.manifest.next_pending_step()
    }

    /// Return `true` when every step is either completed or skipped.
    #[must_use]
    pub fn is_complete(&self) -> bool {
        self.manifest.is_complete()
    }

    /// Mark `step` as in-progress and notify the observer.
    ///
    /// Returns `true` when the step exists and was pending.
    pub fn start_step(&mut self, step: RunStep, observer: &dyn TierRouterObserver) -> bool {
        let started = self.manifest.start_step(step);
        if started {
            observer.on_step(step, StepStatus::InProgress, None);
        }
        started
    }

    /// Mark `step` as completed and notify the observer.
    pub fn finish_step(&mut self, step: RunStep, observer: &dyn TierRouterObserver) -> bool {
        let finished = self.manifest.complete_step(step);
        if finished {
            observer.on_step(step, StepStatus::Completed, None);
        }
        finished
    }

    /// Run `step` if it is the next pending step, otherwise return `default`.
    ///
    /// This helper encapsulates the repeated `next_step()` / `start_step()` /
    /// `finish_step()` boilerplate used throughout the session dispatch loop.
    /// When the next pending step matches `step`, the closure `f` is called
    /// between `start_step` and `finish_step`, and its return value is
    /// wrapped in `Some`. When the next step does not match, `None` is
    /// returned immediately without calling `f`.
    ///
    /// # Example
    ///
    /// ```ignore
    /// let graph: Option<ContradictionGraph> = router.run_step_if(
    ///     RunStep::ContradictionGraph,
    ///     &router_observer,
    ///     || { Some(build_contradiction_graph(&sources)) },
    /// );
    /// ```
    pub fn run_step_if<T, F>(
        &mut self,
        step: RunStep,
        observer: &dyn TierRouterObserver,
        f: F,
    ) -> Option<T>
    where
        F: FnOnce() -> T,
    {
        if self.next_step() == Some(step) {
            self.start_step(step, observer);
            let result = f();
            self.finish_step(step, observer);
            Some(result)
        } else {
            None
        }
    }

    /// Mark `step` as skipped, optionally recording a reason.
    pub fn skip_step(
        &mut self,
        step: RunStep,
        detail: Option<String>,
        observer: &dyn TierRouterObserver,
    ) -> bool {
        let skipped = self.manifest.skip_step(step, detail.clone());
        if skipped {
            observer.on_step(step, StepStatus::Skipped, detail);
        }
        skipped
    }

    /// Mark `step` as failed, optionally recording a reason.
    pub fn fail_step(
        &mut self,
        step: RunStep,
        detail: Option<String>,
        observer: &dyn TierRouterObserver,
    ) -> bool {
        let failed = self.manifest.fail_step(step, detail.clone());
        if failed {
            observer.on_step(step, StepStatus::Failed, detail);
        }
        failed
    }

    /// Mark the entire run as completed and notify the observer.
    pub fn complete_run(&mut self, observer: &dyn TierRouterObserver) {
        let completed = self
            .manifest
            .steps
            .iter()
            .filter(|s| s.status == StepStatus::Completed)
            .count();
        let skipped = self
            .manifest
            .steps
            .iter()
            .filter(|s| s.status == StepStatus::Skipped)
            .count();
        let failed = self
            .manifest
            .steps
            .iter()
            .filter(|s| s.status == StepStatus::Failed)
            .count();
        self.manifest.complete_run();
        observer.on_done(completed, skipped, failed);
    }

    /// Mark all pending or failed steps for the current tier as skipped.
    ///
    /// This is a convenience helper used when the run must terminate early
    /// without reaching the normal end of the pipeline (e.g. a fatal error).
    pub fn skip_remaining(&mut self, reason: &str, observer: &dyn TierRouterObserver) {
        let pending: Vec<RunStep> = self
            .manifest
            .steps
            .iter()
            .filter(|s| {
                s.status == StepStatus::Pending
                    || s.status == StepStatus::InProgress
                    || s.status == StepStatus::Failed
            })
            .map(|s| s.step)
            .collect();
        for step in pending {
            self.skip_step(step, Some(reason.to_string()), observer);
        }
    }

    /// Advance through all remaining steps, applying the supplied closure to
    /// each step in order.
    ///
    /// The closure receives the router (so it can call start/finish/skip/fail),
    /// the step, and the observer. It returns `Ok(())` to indicate the step was
    /// handled; the router then moves to the next pending step. If the closure
    /// returns `Err`, the current step is marked failed and the walk stops.
    ///
    /// This is primarily a test/utility helper; the real session will drive
    /// steps explicitly because each step has different concrete work.
    pub fn walk_remaining<F, E: ToString>(
        &mut self,
        observer: &dyn TierRouterObserver,
        mut handle: F,
    ) -> Result<(), E>
    where
        F: FnMut(&mut Self, RunStep, &dyn TierRouterObserver) -> Result<(), E>,
    {
        while let Some(step) = self.next_step() {
            self.start_step(step, observer);
            if let Err(e) = handle(self, step, observer) {
                self.fail_step(step, Some(e.to_string()), observer);
                return Err(e);
            }
            if self.next_step() == Some(step) {
                // The handler neither completed nor skipped/failed the step.
                // Skip it to avoid an infinite loop.
                self.skip_step(
                    step,
                    Some("handler did not finish step".to_string()),
                    observer,
                );
            }
        }
        let (completed, skipped, failed) = self.counts();
        observer.on_done(completed, skipped, failed);
        Ok(())
    }

    /// Count steps by terminal status.
    #[must_use]
    pub fn counts(&self) -> (usize, usize, usize) {
        let completed = self
            .manifest
            .steps
            .iter()
            .filter(|s| s.status == StepStatus::Completed)
            .count();
        let skipped = self
            .manifest
            .steps
            .iter()
            .filter(|s| s.status == StepStatus::Skipped)
            .count();
        let failed = self
            .manifest
            .steps
            .iter()
            .filter(|s| s.status == StepStatus::Failed)
            .count();
        (completed, skipped, failed)
    }

    /// Serialize the manifest to pretty JSON.
    pub fn manifest_json(&self) -> crate::run_manifest::Result<String> {
        self.manifest.to_json()
    }
}

/// Helper for creating a default run tag from a name and timestamp.
#[must_use]
pub fn default_run_tag(name: &str) -> String {
    let ts = chrono::Utc::now().format("%Y%m%d-%H%M%S").to_string();
    format!("{name}-{ts}")
}

/// Adapter that forwards tier-router events as [`SessionEvent`](crate::session::SessionEvent).
///
/// This bridges the router's observer trait to the existing session observer
/// stream, so the CLI/TUI see `RunStep` events as ordinary session events.
#[derive(Clone)]
pub struct TierRouterToSessionObserver {
    inner: Arc<dyn crate::session::SessionObserver>,
}

impl TierRouterToSessionObserver {
    /// Wrap an existing session observer.
    #[must_use]
    pub fn new(inner: Arc<dyn crate::session::SessionObserver>) -> Self {
        Self { inner }
    }
}

impl TierRouterObserver for TierRouterToSessionObserver {
    fn on_step(&self, step: RunStep, status: StepStatus, detail: Option<String>) {
        self.inner.on_event(crate::session::SessionEvent::RunStep {
            step: step.as_str().to_string(),
            status: status.as_str().to_string(),
            detail,
        });
    }

    fn on_done(&self, completed: usize, skipped: usize, failed: usize) {
        self.inner.on_event(crate::session::SessionEvent::TierDone {
            completed,
            skipped,
            failed,
        });
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::run_config::Tier;

    #[test]
    fn router_defaults_to_full_tier() {
        let router = TierRouter::new("run-1", "glp1", "GLP-1 outcomes", Tier::default());
        assert_eq!(router.tier(), Tier::Full);
        let steps: Vec<_> = router.manifest().steps.iter().map(|s| s.step).collect();
        assert!(steps.contains(&RunStep::ContradictionGraph));
        assert!(steps.contains(&RunStep::ReadabilityAudit));
    }

    #[test]
    fn light_router_skips_adversarial_steps() {
        let router = TierRouter::new("run-1", "demo", "demo topic", Tier::Light);
        let steps: Vec<_> = router.manifest().steps.iter().map(|s| s.step).collect();
        assert!(steps.contains(&RunStep::Decompose));
        assert!(steps.contains(&RunStep::WidthSweep));
        assert!(steps.contains(&RunStep::Polish));
        assert!(!steps.contains(&RunStep::ContradictionGraph));
        assert!(!steps.contains(&RunStep::LociAnalysis));
        assert!(!steps.contains(&RunStep::ReadabilityAudit));
    }

    #[test]
    fn full_router_includes_all_steps() {
        let router = TierRouter::new("run-1", "demo", "demo topic", Tier::Full);
        let steps: Vec<_> = router.manifest().steps.iter().map(|s| s.step).collect();
        assert!(steps.contains(&RunStep::ContradictionGraph));
        assert!(steps.contains(&RunStep::Critics));
        assert!(steps.contains(&RunStep::ReadabilityAudit));
    }

    #[test]
    fn dissertation_router_starts_with_chapter_partition() {
        let router = TierRouter::new("run-1", "demo", "demo topic", Tier::Dissertation);
        let steps: Vec<_> = router.manifest().steps.iter().map(|s| s.step).collect();
        assert_eq!(steps[0], RunStep::ChapterPartition);
        assert!(steps.contains(&RunStep::Synthesize));
    }

    #[test]
    fn walk_remaining_runs_steps_in_order() {
        let mut router = TierRouter::new("run-1", "demo", "demo topic", Tier::Light);
        let observer = CollectingTierRouterObserver::new();
        let steps_to_run: Vec<RunStep> = router.manifest().steps.iter().map(|s| s.step).collect();
        router
            .walk_remaining(&observer, |r, step, obs| {
                if steps_to_run.contains(&step) {
                    r.finish_step(step, obs);
                }
                Ok::<(), std::convert::Infallible>(())
            })
            .unwrap();
        assert!(router.is_complete());
        let events = observer.events();
        let completed = events
            .iter()
            .filter(|(_, s, _)| *s == StepStatus::Completed)
            .count();
        assert_eq!(completed, RunStep::steps_for_tier(Tier::Light).len());
    }

    #[test]
    fn skip_remaining_marks_pending_steps_skipped() {
        let mut router = TierRouter::new("run-1", "demo", "demo topic", Tier::Full);
        let observer = CollectingTierRouterObserver::new();
        router.start_step(RunStep::Decompose, &observer);
        router.finish_step(RunStep::Decompose, &observer);
        router.skip_remaining("early termination", &observer);
        let events = observer.events();
        let skipped = events
            .iter()
            .filter(|(_, s, _)| *s == StepStatus::Skipped)
            .count();
        assert_eq!(skipped, RunStep::steps_for_tier(Tier::Full).len() - 1);
    }

    #[test]
    fn supervisor_router_uses_graph_steps() {
        let router = TierRouter::new_with_mode(
            "run-sv",
            "demo",
            "demo topic",
            Tier::Full,
            ResearchMode::Supervisor,
        );
        assert_eq!(router.mode(), ResearchMode::Supervisor);
        let steps: Vec<_> = router.manifest().steps.iter().map(|s| s.step).collect();
        assert_eq!(
            steps,
            vec![
                RunStep::SupervisorPlan,
                RunStep::SupervisorDelegate,
                RunStep::SupervisorSynthesize,
                RunStep::SupervisorFinalize,
            ]
        );
    }

    #[test]
    fn competitive_router_uses_graph_steps() {
        let router = TierRouter::new_with_mode(
            "run-comp",
            "demo",
            "demo topic",
            Tier::Full,
            ResearchMode::Competitive,
        );
        assert_eq!(router.mode(), ResearchMode::Competitive);
        let steps: Vec<_> = router.manifest().steps.iter().map(|s| s.step).collect();
        assert_eq!(
            steps,
            vec![
                RunStep::SupervisorPlan,
                RunStep::SupervisorDelegate,
                RunStep::SupervisorSynthesize,
                RunStep::SupervisorFinalize,
            ]
        );
    }

    #[test]
    fn supervisor_router_walks_graph_steps() {
        let mut router = TierRouter::new_with_mode(
            "run-sv",
            "demo",
            "demo topic",
            Tier::Full,
            ResearchMode::Supervisor,
        );
        let observer = CollectingTierRouterObserver::new();
        router
            .walk_remaining(&observer, |r, step, obs| {
                r.finish_step(step, obs);
                Ok::<(), std::convert::Infallible>(())
            })
            .unwrap();
        assert!(router.is_complete());
        let events = observer.events();
        let completed = events
            .iter()
            .filter(|(_, s, _)| *s == StepStatus::Completed)
            .count();
        assert_eq!(completed, 4);
    }
}
