//! Guardrails for spawning the compiler/runner programs a benchmark fixture asks for.
//!
//! SEC-ragent-bench-001 (SECTASKS T-009): each fixture carries an
//! `execution_commands: Vec<Vec<String>>` list that the native harnesses used
//! to spawn verbatim (`[0]` as the program, the rest as argv). A fixture is
//! corpus content - supplied by a cloned repository, a downloaded dataset, or
//! `/bench init` - so an attacker-controlled entry such as
//! `["/bin/sh", "-c", "<payload>"]` executed as the user with the benchmark's
//! full privileges and no allowlist check.
//!
//! This module makes the program set explicit:
//!
//! - only allowlisted toolchain programs may be spawned;
//! - the program must be a bare name (no path separator, no `..`, not
//!   absolute), so it is resolved on `PATH` and cannot name an arbitrary
//!   binary inside the fixture directory;
//! - shell interpreters (`sh`, `bash`, `env`, ...) are never allowed, so a
//!   one-token payload cannot be smuggled through a wrapper.

/// Programs a benchmark fixture is allowed to invoke.
///
/// This is the intended toolchain set the native harnesses target, plus the
/// interpreters used to *run* an already-compiled artefact (`java`, `python3`,
/// `node`) and the `timeout` wrapper the harness prepends itself.
pub const ALLOWED_FIXTURE_PROGRAMS: &[&str] = &[
    // C / C++
    "gcc", "g++", "cc", "clang", "clang++", // Rust
    "rustc",   // Go
    "go",      // Java
    "javac", "java", // Node / TypeScript
    "node", "tsc", // PHP / Ruby
    "php", "ruby", // Python (running a compiled/checked artefact, not a shell)
    "python3", "python",
];

/// Base names of the artefacts the native harnesses themselves produce.
///
/// A second `execution_commands` entry runs the binary compiled by the first
/// (`["./candidate.rs.exe"]`). That path is *generated by the harness*, not
/// chosen by the fixture, so it cannot name an arbitrary binary - but the
/// guard still checks the name against this fixed set rather than accepting
/// any `./` path.
pub const ALLOWED_ARTEFACT_PREFIXES: &[&str] = &[
    // MBPP harness source name: `candidate.<ext>`.
    "candidate",
    // HumanEval harness source name: `humaneval.<ext>`.
    "humaneval",
];

/// Extensions a harness-produced artefact may carry.
pub const ALLOWED_ARTEFACT_EXTENSIONS: &[&str] = &[
    "exe", "out", "bin", "class", "jar", "pyc", "js", "rb", "php",
];

/// Whether `program` may be spawned by a benchmark fixture.
///
/// Accepts a bare allowlisted toolchain name, or a fixture-relative
/// `./<artefact>` reference to one of the binaries the harness itself
/// compiled ([`ALLOWED_ARTEFACT_NAMES`]). Rejects absolute paths, `..`,
/// directory traversal, and shell/command interpreters.
#[must_use]
pub fn is_allowed_fixture_program(program: &str) -> bool {
    let candidate = program.trim();
    if candidate.is_empty() {
        return false;
    }
    if let Some(relative) = candidate.strip_prefix("./") {
        return is_harness_artefact(relative);
    }
    // Any remaining separator means the fixture is naming a specific file.
    if candidate.contains('/') || candidate.contains('\\') {
        return false;
    }
    if candidate == ".." || candidate == "." {
        return false;
    }
    ALLOWED_FIXTURE_PROGRAMS.contains(&candidate)
}

/// Whether `relative` (already `./`-stripped) names a harness-produced artefact.
///
/// The harness writes the source as `<prefix>.<ext>` and compiles it to
/// `<prefix>.<ext>.exe`, so the accepted shape is a single plain component
/// whose stem starts with an [`ALLOWED_ARTEFACT_PREFIXES`] entry and whose
/// final extension is in [`ALLOWED_ARTEFACT_EXTENSIONS`]. No separators, no
/// `..`, no absolute paths.
fn is_harness_artefact(relative: &str) -> bool {
    if relative.is_empty()
        || relative.contains('/')
        || relative.contains('\\')
        || relative == ".."
        || relative == "."
    {
        return false;
    }
    let Some(stem) = relative.split('.').next() else {
        return false;
    };
    if !ALLOWED_ARTEFACT_PREFIXES.contains(&stem) {
        return false;
    }
    match relative.rsplit_once('.') {
        Some((_, ext)) => ALLOWED_ARTEFACT_EXTENSIONS.contains(&ext),
        None => false,
    }
}

/// Validate a fixture-supplied command list before it is spawned.
///
/// # Errors
///
/// Returns a message naming the offending program when the list is empty or
/// its first element is not an allowed fixture program.
pub fn validate_fixture_command(command_parts: &[String]) -> Result<(), String> {
    let Some(program) = command_parts.first() else {
        return Err("fixture command list was empty".to_string());
    };
    if !is_allowed_fixture_program(program) {
        return Err(format!(
            "fixture command program '{program}' is not an allowlisted toolchain \
             program (allowed: {})",
            ALLOWED_FIXTURE_PROGRAMS.join(", ")
        ));
    }
    Ok(())
}

/// Hard wall-clock timeout applied to a `python3` hidden-test subprocess.
///
/// SEC-ragent-bench-002 (SECTASKS T-009/T-048): the hidden-test paths only had
/// an in-script `signal.alarm`, which untrusted fixture code defeats with
/// `signal.alarm(0)`. The subprocess is wrapped in `timeout` with this budget
/// so the benchmark can never hang indefinitely.
pub const FIXTURE_SUBPROCESS_TIMEOUT_SECS: u64 = 30;
