//! Project documentation scaffold (FR-019, T-017).
//!
//! Renders the documentation layer every `/new` scaffold receives on top of
//! the code and workspace artifacts:
//!
//! - `README.md` — project title (directory name), one-paragraph description,
//!   and language/app-type-specific build-and-run instructions;
//! - `QUICKSTART.md` — a minimal get-running guide: prerequisites, the exact
//!   build-and-run command, and the expected first output;
//! - `STATS.md` — initial project statistics: generation timestamp (UTC),
//!   language, app type, stack (or none), generated-file count, and the
//!   ragent version that produced the scaffold;
//! - `docs/` — a documentation folder, materialised via a `docs/README.md`
//!   placeholder so the existing file emitter creates it.
//!
//! NFR-002 (template consistency): every build/run instruction is rendered
//! from the same [`LanguageRecipe`] data that produces the code artifacts —
//! the run command, the test command, and the entrypoint path all come from
//! the recipe, so the documentation can never drift from the generated
//! project.
//!
//! Pure planner: no filesystem access, no clock access. The caller supplies
//! the UTC timestamp and version so the module stays deterministic and
//! testable.

use super::emit::PlannedArtifact;
use super::flags::{AppType, Language};
use super::recipes::LanguageRecipe;

/// One planned documentation file: path relative to the scaffold root plus
/// full rendered content.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DocFile {
    /// Path relative to the scaffold root, forward slashes, no leading `/`.
    pub path: &'static str,
    /// Full file content (UTF-8, LF line endings).
    pub content: String,
}

impl PlannedArtifact for DocFile {
    fn artifact_path(&self) -> &str {
        self.path
    }

    fn artifact_content(&self) -> &str {
        &self.content
    }
}

/// One-paragraph project description (FR-019 README requirement).
fn description(language: Language, app_type: AppType) -> String {
    format!(
        "A {app_type} project written in {language}, generated by the ragent \
         `/new` scaffolding command with a minimal, runnable hello-world \
         artifact set and the ragent workspace layout."
    )
}

/// Render `README.md` (FR-019): title, description, build-and-run
/// instructions derived from the recipe.
fn readme(recipe: &LanguageRecipe, app_type: AppType, project_name: &str) -> String {
    let run = recipe.run_command;
    let test = recipe.test_command;
    let entrypoint = recipe
        .source_for(app_type)
        .map(|file| file.path)
        .unwrap_or("(no entrypoint)");
    format!(
        "# {project_name}\n\
         \n\
         {desc}\n\
         \n\
         ## Requirements\n\
         \n\
         Install the {language} toolchain for your platform, then build and run\n\
         from this directory.\n\
         \n\
         ## Build and Run\n\
         \n\
         - Entry point: `{entrypoint}`\n\
         - Run: `{run}`\n\
         - Test: `{test}`\n\
         \n\
         ## Project Layout\n\
         \n\
         - `.ragent/` - ragent project configuration and custom agents\n\
         - `specs/` - project specifications (manage with ragent /spec)\n\
         - `log/` - runtime logs (gitignored)\n\
         - `docs/` - project documentation\n\
         - `AGENTS.md` - guidelines for the ragent agent\n",
        project_name = project_name,
        desc = description(recipe.language, app_type),
        language = recipe.language,
        entrypoint = entrypoint,
        run = run,
        test = test,
    )
}

/// Render `QUICKSTART.md` (FR-019): prerequisites, exact run command, and
/// expected first output.
fn quickstart(recipe: &LanguageRecipe, app_type: AppType) -> String {
    format!(
        "# Quickstart\n\
         \n\
         ## Prerequisites\n\
         \n\
         A {language} toolchain must be installed and on your `PATH`.\n\
         See the official {language} installation guide for your platform.\n\
         \n\
         ## Run\n\
         \n\
         From this directory run:\n\
         \n\
         ```\n\
         {run}\n\
         ```\n\
         \n\
         ## Expected output\n\
         \n\
         ```\n\
         Hello, world!\n\
         ```\n\
         \n\
         ## Next steps\n\
         \n\
         - Run the tests: `{test}`\n\
         - Edit the entry point: `{entrypoint}`\n",
        language = recipe.language,
        run = recipe.run_command,
        test = recipe.test_command,
        entrypoint = recipe
            .source_for(app_type)
            .map(|file| file.path)
            .unwrap_or("(no entrypoint)"),
    )
}

/// Render `STATS.md` (FR-019): generation timestamp (UTC), language, app
/// type, stack (or none), generated-file count, and producing ragent version.
fn stats(
    recipe: &LanguageRecipe,
    app_type: AppType,
    stack: Option<&str>,
    generated_files: usize,
    generated_at_utc: &str,
    ragent_version: &str,
) -> String {
    let stack_text = stack.unwrap_or("none");
    format!(
        "# Project Statistics\n\
         \n\
         - Generated at: {generated_at_utc}\n\
         - Language: {language}\n\
         - App type: {app_type}\n\
         - Stack: {stack_text}\n\
         - Generated files: {generated_files}\n\
         - Generated by: ragent {ragent_version}\n",
        generated_at_utc = generated_at_utc,
        language = recipe.language,
        app_type = app_type,
        stack_text = stack_text,
        generated_files = generated_files,
        ragent_version = ragent_version,
    )
}

/// Placeholder content for `docs/README.md`, which materialises the FR-019
/// `docs/` folder through the normal emitter (parent directories are created
/// automatically, so the folder exists after emission even when empty).
const DOCS_PLACEHOLDER: &str = "# Documentation\n\nProject documentation lives in this folder.\n";

/// Plan the FR-019 documentation file set for a scaffold.
///
/// `generated_files` is the count of code + workspace files already planned
/// (the STATS figure); `generated_at_utc` is the caller-rendered UTC
/// timestamp string; `ragent_version` is the version of the ragent binary
/// producing the scaffold.
pub fn doc_artifacts(
    recipe: &LanguageRecipe,
    app_type: AppType,
    project_name: &str,
    stack: Option<&str>,
    generated_files: usize,
    generated_at_utc: &str,
    ragent_version: &str,
) -> Vec<DocFile> {
    vec![
        DocFile {
            path: "README.md",
            content: readme(recipe, app_type, project_name),
        },
        DocFile {
            path: "QUICKSTART.md",
            content: quickstart(recipe, app_type),
        },
        DocFile {
            path: "STATS.md",
            content: stats(
                recipe,
                app_type,
                stack,
                generated_files,
                generated_at_utc,
                ragent_version,
            ),
        },
        DocFile {
            path: "docs/README.md",
            content: DOCS_PLACEHOLDER.to_owned(),
        },
    ]
}
